### PR TITLE
Add Neil Fraser original repo as gitmodule

### PR DESCRIPTION
**Pull request by marashiai**
This Pull Request will remove the code copied from the original repo https://github.com/NeilFraser/JS-Interpreter and will use `gitmodules` to clone the repo directly before build.

The idea was first presented by @mercmobily in this repo: https://github.com/mercmobily/js-interpreter and was discussed in this issue: https://github.com/NeilFraser/JS-Interpreter/issues/172

This PR will use a similar approach, removing the additional changes made in this repo and publish them as a separate NPM package, leaving the https://www.npmjs.com/package/js-interpreter completely identical to the original repo https://github.com/NeilFraser/JS-Interpreter.

### CODE REVIEW

**Comment by mercmobily** [comment]
I just wanted to say that you don't need to have a repository marked as a "fork" of Neil's. Since the original repo for JS Interpreter is as a submodule, you will never actually merge this repo with Neil's... It's just semantic; if I were you, I'd make a new fresh repo, with the same name and URL, but not marked as a fork since it's incorrect information, formally speaking.

**Comment by marashiai** [comment]
@mercmobily Package is uploaded on `js-interpreter@2.0.0-beta.1` please feel free to test and let me know what you think.

**Review by aaimio — APPROVED** [review]

**Review by aaimio — APPROVED** [review]

**Comment by mercmobily** [comment]
I managed to have a look. A few notes:

* You used Webpack rather than a much more basic "sandwitching" I did. This opens up the possibility of minifying the code. However, there are cases where you want the code un-minified. This could be for development, or for including it in a project that will then get minified. Please provide an un-minified version too.

* I love the fact that you created a CLI for it

* Please upgrade to the latest repo. There were some very important fixes over the last couple of weeks

* I think you should check the dependencies for i in package.json. For example, you are using js-interpreter's version of acorn, and yet you have acorn as a dependency. Also, you have babel in package.json -- are you sure you need it? As far as I can see, js-interpreter doesn't use ES6; besides, I *think* (I might be wrong) that you are not actually using babel.

* The repository is still a 'fork' of js-interpreter. However, this is not really a fork. But, it's up to you.

Thank you for this, nicely done. Once you publish it, I will unpublish mine and will definitely recommend this as "the" NPM module for this project.

**Comment by mercmobily** [comment]
I hope my comments/requests make sense. Sorry if I sounded pushy! It's free software, so no deadline there at all! Please let me know how it's looking though -- I would love to start using your NPM sooner rather than later.

**Comment by marashiai** [comment]
@mercmobily Sorry it took a while, the latest version is published: https://www.npmjs.com/package/js-interpreter (2.1.0 is up-to-date with the original repo).

**Pull request merged**
