### PR TITLE
Add command line interface for executing js files using the interpreter

### PR DESCRIPTION
**Pull request by pcardune**
Thanks for turning this project into an npm package! I'm looking into potentially using it for [code.org](https://github.com/code-dot-org/code-dot-org).

As part of using this package, I'm working on hooking up the [Official ECMAScript Conformance Test Suite](https://github.com/tc39/test262) using https://github.com/bterlson/test262-harness. It's pretty easy to hook up if you have a command line interface, so I've added one with this pull request.

### CODE REVIEW

**Comment by marashiai** [comment]
I published your package in `js-interpreter@1.2.0-alpha.2`, but it does not seem to work.
```
Error: Cannot find module '../src/interpreter'
```
Edit: When I change that to `require('../lib')` throws another error:
```
SyntaxError: Unexpected character '#' (1:0)
```
I guess we need to add it to the webpack build process.

**Comment by pcardune** [comment]
yep. I think we do need to add it to the webpack build process. I'll take a look and update this PR.

Also, for my purposes, I'm trying to upgrade our codebase from an older version of JSInterpreter, which is going to be a bit complicated because we do all kinds of crazy things with the internals.

As a result, I've published a separate package under the @code-dot-org namespace (https://www.npmjs.com/package/@code-dot-org/js-interpreter) which looks very similar to this one but has an old version of JSInterpreter. I don't expect anyone but us to use it, and I hope that once we've upgraded our internal usage of the interpreter, we can switch to your package.

Just out of curiosity, what are you using this interpreter for and what are your plans for maintaining this package? We have a number of improvements we'd like to make, and judging by the inactivity on Neil Fraser's repo, we're considering just developing on our own fork without attempting to contribute back upstream.

**Comment by marashiai** [comment]
We are going to use it for sandboxing our strategy generator [Binary Bot](https://bot.binary.com). In our case, the current functionality seems to be enough for now, but maybe we decide to add more features in the future.
One thing that can be improved in our case though is the performance regarding both memory and CPU usage.

**Comment by marashiai** [comment]
I fixed the issue and published `1.3.0` with cli support. Thank you @pcardune

**Pull request closed without merging**
